
2022-01-24 16:15:42,994 ERROR: 
Exception on /admin/ [GET] [in /home/jagdpanther/EPAM/snaketests/venv/lib/python3.8/site-packages/flask/app.py:1457]
Traceback (most recent call last):
  File "/home/jagdpanther/EPAM/snaketests/venv/lib/python3.8/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/jagdpanther/EPAM/snaketests/venv/lib/python3.8/site-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/jagdpanther/EPAM/snaketests/venv/lib/python3.8/site-packages/flask_restful/__init__.py", line 271, in error_router
    return original_handler(e)
  File "/home/jagdpanther/EPAM/snaketests/venv/lib/python3.8/site-packages/flask_restful/__init__.py", line 271, in error_router
    return original_handler(e)
  File "/home/jagdpanther/EPAM/snaketests/venv/lib/python3.8/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/jagdpanther/EPAM/snaketests/venv/lib/python3.8/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/jagdpanther/EPAM/snaketests/venv/lib/python3.8/site-packages/flask_admin/base.py", line 65, in inner
    abort = self._handle_view(f.__name__, **kwargs)
  File "/home/jagdpanther/EPAM/snaketests/venv/lib/python3.8/site-packages/flask_admin/base.py", line 353, in _handle_view
    if not self.is_accessible():
TypeError: is_accessible() missing 1 required positional argument: 'self'

2022-01-24 16:15:45,338 ERROR: 
Exception on /admin/ [GET] [in /home/jagdpanther/EPAM/snaketests/venv/lib/python3.8/site-packages/flask/app.py:1457]
Traceback (most recent call last):
  File "/home/jagdpanther/EPAM/snaketests/venv/lib/python3.8/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/jagdpanther/EPAM/snaketests/venv/lib/python3.8/site-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/jagdpanther/EPAM/snaketests/venv/lib/python3.8/site-packages/flask_restful/__init__.py", line 271, in error_router
    return original_handler(e)
  File "/home/jagdpanther/EPAM/snaketests/venv/lib/python3.8/site-packages/flask_restful/__init__.py", line 271, in error_router
    return original_handler(e)
  File "/home/jagdpanther/EPAM/snaketests/venv/lib/python3.8/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/jagdpanther/EPAM/snaketests/venv/lib/python3.8/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/jagdpanther/EPAM/snaketests/venv/lib/python3.8/site-packages/flask_admin/base.py", line 65, in inner
    abort = self._handle_view(f.__name__, **kwargs)
  File "/home/jagdpanther/EPAM/snaketests/venv/lib/python3.8/site-packages/flask_admin/base.py", line 353, in _handle_view
    if not self.is_accessible():
TypeError: is_accessible() missing 1 required positional argument: 'self'

2022-01-24 16:15:49,968 ERROR: 
Exception on /admin/ [GET] [in /home/jagdpanther/EPAM/snaketests/venv/lib/python3.8/site-packages/flask/app.py:1457]
Traceback (most recent call last):
  File "/home/jagdpanther/EPAM/snaketests/venv/lib/python3.8/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/jagdpanther/EPAM/snaketests/venv/lib/python3.8/site-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/jagdpanther/EPAM/snaketests/venv/lib/python3.8/site-packages/flask_restful/__init__.py", line 271, in error_router
    return original_handler(e)
  File "/home/jagdpanther/EPAM/snaketests/venv/lib/python3.8/site-packages/flask_restful/__init__.py", line 271, in error_router
    return original_handler(e)
  File "/home/jagdpanther/EPAM/snaketests/venv/lib/python3.8/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/jagdpanther/EPAM/snaketests/venv/lib/python3.8/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/jagdpanther/EPAM/snaketests/venv/lib/python3.8/site-packages/flask_admin/base.py", line 65, in inner
    abort = self._handle_view(f.__name__, **kwargs)
  File "/home/jagdpanther/EPAM/snaketests/venv/lib/python3.8/site-packages/flask_admin/base.py", line 353, in _handle_view
    if not self.is_accessible():
TypeError: is_accessible() missing 1 required positional argument: 'self'
